#!/bin/sh

dirs=("html" "css" "img" "js")
for dir in ${dirs[@]}; do
echo "Entering directory $dir"
cd $dir
if [ $? -eq 0 ]; then
	rm -f *~
	echo "creating zip file"
	zip $dir *
	mv "$dir.zip" ../
	cd ..
fi
echo "Leaving directory " $dir
done
